---
# Based in travis conf from:
# 1. https://github.com/sudo-suhas/symcrypto/blob/master/.travis.yml
# 2. https://gist.github.com/y0ssar1an/df2dab474520c4086926f672c52db139

dist: trusty
addons:
  sonarcloud:
    organization: joaodubas-github
language: go
go:
  - 1.10
  - 1.9
  - 1.8
install: true
notifciations:
  email: false
before_script:
  # Setup env vars to make lint/tests easier
  - GO_FILES=$(find . -iname '*.go' | grep -v /vendor/)  # All the .go files, excluding vendor/
  # Install linters
  - go get -u github.com/golang/lint/golint
  - go get -u honnef.co/go/tools/cmd/megacheck
  - go get -u github.com/fzipp/gocyclo
  - go get -u github.com/kisielk/errcheck
  # Install goveralls, Go integration coveralls.io
  - go get -u github.com/mattn/goveralls
  # Install codeclimate test report
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - test -z $(gofmt -s -l $GO_FILES)  # Fail if a .go file hasn't been formatted with gofmt
  - go vet ./...                      # go vet is the official Go static analyzer
  - megacheck ./...                   # "go vet" on steroids + linter
  - errcheck ./...                    # Check for unchecked errors
  - gocyclo -over 19 $GO_FILES        # forbid code with huge functions
  - golint -set_exit_status ./...     # One last linter
  # Run all tests
  - go test -v -covermode=count -coverprofile=coverage.txt ./...
  - goveralls -coverprofile=coverage.txt -service=travis-ci
  # Scan project to sonarcloud
  - sonar-scanner
after_script:
  # Upload coverage report to codeclimate
  - cp coverage.txt c.out
  - ./cc-test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT
after_success:
  # Upload coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)